package io.nessus.identity.types

import io.kotest.matchers.collections.shouldContain
import io.kotest.matchers.equals.shouldBeEqual
import kotlinx.serialization.json.*
import kotlin.test.Test

class W3CCredentialTest {

    @Test
    fun testW3CCredentialV11Ebsi32() {

        val credJwt = W3CCredentialV11Jwt.fromEncoded(
            "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDplYnNpOnpqSFpqSjRTeTdyOTJCeFh6RkdzN3FEI1Q2aVBNVy1rOE80dXdaaWQyOUd3TGUtTmpnNDBFNmpOVDdoZExwSjNaU2ciLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3NjAwOTkyMjksImV4cCI6MTc2MDE4NTYzNCwianRpIjoidmM6ZWJzaTpjb25mb3JtYW5jZSNjYWUyOTMzZS1jNmUxLTQ5YjItOTg1Zi00NGYxYWM4MGVmNWYiLCJzdWIiOiJkaWQ6a2V5OnoyZG16RDgxY2dQeDhWa2k3SmJ1dU1tRllyV1BnWW95dHlrVVozZXlxaHQxajlLYm5oZWZwTTE0VXVTcUpEaUN6QjJMQ2RUZ1JabzhKZW1DTEhXbWhZcWpDY2JkejQ5R2FlWTl1Z0QxaTJRdzhTbzZ3VGlTcXlnVVR0OTNvVWplVjFkeHpNemFVTEJ4VE5vb2R3eGNqdXc2a0t5NWVCNDN2ZXFGWnh6QVF1NVZ1V1FnbWEiLCJpc3MiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsIm5iZiI6MTc2MDA5OTIyOSwidmMiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiY3JlZGVudGlhbFNjaGVtYSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1zY2hlbWFzLXJlZ2lzdHJ5L3YzL3NjaGVtYXMvekRwV0dVQmVubXFYenVyc2tyeTlOc2s2dnEyUjh0aGg5VlNlb1JxZ3VveU1EIiwidHlwZSI6IkZ1bGxKc29uU2NoZW1hVmFsaWRhdG9yMjAyMSJ9LCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDprZXk6ejJkbXpEODFjZ1B4OFZraTdKYnV1TW1GWXJXUGdZb3l0eWtVWjNleXFodDFqOUtibmhlZnBNMTRVdVNxSkRpQ3pCMkxDZFRnUlpvOEplbUNMSFdtaFlxakNjYmR6NDlHYWVZOXVnRDFpMlF3OFNvNndUaVNxeWdVVHQ5M29VamVWMWR4ek16YVVMQnhUTm9vZHd4Y2p1dzZrS3k1ZUI0M3ZlcUZaeHpBUXU1VnVXUWdtYSJ9LCJleHBpcmF0aW9uRGF0ZSI6IjIwMjUtMTAtMTFUMTI6Mjc6MTRaIiwiaWQiOiJ2YzplYnNpOmNvbmZvcm1hbmNlI2NhZTI5MzNlLWM2ZTEtNDliMi05ODVmLTQ0ZjFhYzgwZWY1ZiIsImlzc3VhbmNlRGF0ZSI6IjIwMjUtMTAtMTBUMTI6Mjc6MDlaIiwiaXNzdWVkIjoiMjAyNS0xMC0xMFQxMjoyNzowOVoiLCJpc3N1ZXIiOiJkaWQ6ZWJzaTp6akhaako0U3k3cjkyQnhYekZHczdxRCIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlQXR0ZXN0YXRpb24iLCJDVFdhbGxldFNhbWVBdXRob3Jpc2VkSW5UaW1lIl0sInZhbGlkRnJvbSI6IjIwMjUtMTAtMTBUMTI6Mjc6MDlaIiwidGVybXNPZlVzZSI6eyJpZCI6Imh0dHBzOi8vYXBpLWNvbmZvcm1hbmNlLmVic2kuZXUvdHJ1c3RlZC1pc3N1ZXJzLXJlZ2lzdHJ5L3Y1L2lzc3VlcnMvZGlkOmVic2k6empIWmpKNFN5N3I5MkJ4WHpGR3M3cUQvYXR0cmlidXRlcy9iY2RiNmJjOTUyYzhjODk3Y2ExZTYwNWZjZTI1ZjgyNjA0Yzc2YzE2ZDQ3OTc3MDAxNGI3YjI2MmI5M2MwMjUwIiwidHlwZSI6Iklzc3VhbmNlQ2VydGlmaWNhdGUifX19.1PxKOsTYnXnxBiqnC1rf_YY4sJsSlle_a3I3gBIji5qWOlKnc0LAYgcWdx-4-K9gZNx6gSLfKL7ojl4cjYQ1hg"
        )

        val jsonObj = credJwt.toJson()
        val vcObj = jsonObj.getValue("vc").jsonObject
        val ctypes = vcObj.getValue("type").jsonArray.map { it.jsonPrimitive.content }
        ctypes shouldContain "CTWalletSameAuthorisedInTime"

        val issuanceDate = vcObj.getValue("issuanceDate").jsonPrimitive.content
        val validFrom = vcObj.getValue("validFrom").jsonPrimitive.content
        val issued = vcObj.getValue("issued").jsonPrimitive.content
        issuanceDate shouldBeEqual validFrom
        issuanceDate shouldBeEqual issued
    }
}
