{{- with .Values.deployments.ebsi_portal }}
---

# EBSI Portal Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebsi-portal
  labels:
    app.kubernetes.io/name: ebsi-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ebsi-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ebsi-portal
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
    spec:
      containers:
        - name: ebsi-portal
          image: {{ .imagePrefix }}{{ .image }}:{{ .version }}
          imagePullPolicy: {{ .pullPolicy }}
          env:
            - name: EBSI__PORT
              value: "9090"
            - name: EBSI__BASE_URL
              value: "https://{{ $.Values.ebsiPortalHost }}"
            - name: EBSI__PREAUTHORIZED_PIN
              value: "1234"
            - name: WALTID__WALLETAPI__BASE_URL
              value: "https://{{ $.Values.waltidWalletApiHost }}"
            - name: WALTID__DEMO_WALLET_URL
              value: "https://{{ $.Values.demoWalletHost }}"
            - name: WALTID__DEV_WALLET_URL
              value: "https://{{ $.Values.devWalletHost }}"
            - name: DATABASE__JDBC_URL
              value: "jdbc:postgresql://postgres:5432/waltid"
            - name: DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 9090
---

# EBSI Portal Service
#
apiVersion: v1
kind: Service
metadata:
  name: ebsi-portal
spec:
  type: ClusterIP
  ports:
    - port: 9090
  selector:
    app.kubernetes.io/name: ebsi-portal
---

# EBSI Portal IngressRoute
#
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ebsi-portal
  labels:
    app.kubernetes.io/name: ebsi-portal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.ebsiPortalHost }}")
      kind: Rule
      services:
        - name: ebsi-portal
          port: 9090
  tls:
    secretName: {{ $.Values.tlsSecret }}
---

{{- end }}
