{{- with .Values.deployments.wallet_api }}
---

# WalletAPI Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-api
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
    spec:
      containers:
        - name: wallet-api
          image: {{ .imagePrefix }}{{ .image }}:{{ .version }}
          imagePullPolicy: {{ .pullPolicy }}
          env:
            - name: ISSUER__BASE_URL
              value: "https://{{ $.Values.oauthApiHost }}/realms/oid4vci"
            - name: WALTID__WALLETAPI__BASE_URL
              value: "http://waltid-wallet-api:7001"
          ports:
            - containerPort: 8001
---

# WalletAPI Service
#
apiVersion: v1
kind: Service
metadata:
  name: wallet-api
spec:
  type: ClusterIP
  ports:
    - port: 8001
  selector:
    app.kubernetes.io/name: wallet-api
---

# WalletAPI IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wallet-api
  labels:
    app.kubernetes.io/name: wallet-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.walletApiHost }}")
      kind: Rule
      services:
        - name: wallet-api
          port: 8001
  tls:
    secretName: {{ $.Values.tlsSecret }}
---

{{- end }}
