{{- with .Values.deployments.waltid_vc_repo }}
---

# VC Repo Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waltid-vc-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: waltid-vc-repo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: waltid-vc-repo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
    spec:
      containers:
        - name: waltid-vc-repo
          image: waltid/vc-repository:{{ .version }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "7103"
          ports:
            - containerPort: 7103
---

# VC Repo Service
#
apiVersion: v1
kind: Service
metadata:
  name: waltid-vc-repo
spec:
  type: ClusterIP
  ports:
    - port: 7103
  selector:
    app.kubernetes.io/name: waltid-vc-repo
---

# VC Repo IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: waltid-vc-repo
  labels:
    app.kubernetes.io/name: waltid-vc-repo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.repoServiceHost }}")
      kind: Rule
      services:
        - name: waltid-vc-repo
          port: 7103
  tls:
    secretName: {{ $.Values.tlsSecret }}
---

{{- end }}
