#
# ansible-playbook -i ansible/inventory.yml ansible/step01-k3s-server.yml
#
---
- name: Install K3S
  hosts: k3s-server
  become: yes

  tasks:
    -
    # Hostname ---------------------------------------------------------------------------------------------------------

    - name: Get external IP address
      ansible.builtin.shell: "curl -s ipinfo.io/ip"
      register: external_ip

    - name: Append {{ K3S_HOSTNAME }} to k3s-server /etc/hosts
      when: "'k3s-server' in group_names"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ external_ip.stdout }} {{ K3S_HOSTNAME }} registry.{{ K3S_HOSTNAME }}"
        create: yes
      register: append_etc_host

    - name: Append {{ K3S_HOSTNAME }} result
      when: "'k3s-server' in group_names"
      ansible.builtin.debug:
        var: append_etc_host

    # K3S Server -------------------------------------------------------------------------------------------------------

    - name: Install k3s
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - --node-label node.kubernetes.io/type=k3s-server --write-kubeconfig-mode 660 --tls-san {{ external_ip.stdout }}
      register: k3s_install

    - name: Install k3s result
      ansible.builtin.debug:
        var: k3s_install

    - name: Create symlink for kubectl
      ansible.builtin.file:
        src: /usr/local/bin/kubectl
        dest: /usr/bin/kubectl
        state: link

    - name: Wait for file to exist
      ansible.builtin.wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        state: present
        timeout: 120
        delay: 5
        sleep: 2
      register: wait_for_file

    - name: Wait for file result
      ansible.builtin.debug:
        var: wait_for_file

    - name: Fetch kubectl version
      ansible.builtin.shell:
        kubectl version
      when: k3s_install.rc == 0
      register: kubectl_version

    - name: Display kubectl version
      ansible.builtin.debug:
        var: kubectl_version.stdout
      when: kubectl_version is defined
